# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    baseDir: %kernel.root_dir%/..

services:
#    'My\ClassName':
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
